[project]
name = "nn-vit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mlx>=0.26.2",
    "numpy>=2.3.1",
    "torch>=2.7.1",
]
